// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjBiK95Aa98qXbhBlopf1zAPc9Z6bFjg',
    appId: '1:19730488060:web:86f5aaedf7c53826545579',
    messagingSenderId: '19730488060',
    projectId: 'faculty-research-app',
    authDomain: 'faculty-research-app.firebaseapp.com',
    storageBucket: 'faculty-research-app.firebasestorage.app',
    measurementId: 'G-41H5FLZ5CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFt2Vcyaizh0E9dM32vqX_q2oopA3zD_A',
    appId: '1:19730488060:android:2c3f6a8c0a908d12545579',
    messagingSenderId: '19730488060',
    projectId: 'faculty-research-app',
    storageBucket: 'faculty-research-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWo9WJpRHJ-oVKdGydcLUmd-qWztqnJu0',
    appId: '1:19730488060:ios:a943341866198a44545579',
    messagingSenderId: '19730488060',
    projectId: 'faculty-research-app',
    storageBucket: 'faculty-research-app.firebasestorage.app',
    iosBundleId: 'com.example.facultyResearchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWo9WJpRHJ-oVKdGydcLUmd-qWztqnJu0',
    appId: '1:19730488060:ios:a943341866198a44545579',
    messagingSenderId: '19730488060',
    projectId: 'faculty-research-app',
    storageBucket: 'faculty-research-app.firebasestorage.app',
    iosBundleId: 'com.example.facultyResearchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcjBiK95Aa98qXbhBlopf1zAPc9Z6bFjg',
    appId: '1:19730488060:web:90721621e259a84a545579',
    messagingSenderId: '19730488060',
    projectId: 'faculty-research-app',
    authDomain: 'faculty-research-app.firebaseapp.com',
    storageBucket: 'faculty-research-app.firebasestorage.app',
    measurementId: 'G-KX6FPT10BH',
  );
}
